"""init book

Revision ID: 75eea1be4b6b
Revises: 
Create Date: 2020-10-18 11:23:30.307866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75eea1be4b6b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("latest_page", sa.Integer(), nullable=True),
        sa.Column("book_path", sa.Text(), nullable=True),
        sa.Column("stop_at_page", sa.Integer(), nullable=True),
        sa.Column("last_read", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book")
    # ### end Alembic commands ###
